CREATE TABLE USER (
	NAME VARCHAR PRIMARY KEY,
	AGE INTEGER NOT NULL,
	STATE VARCHAR NOT NULL,
	ROLE VARCHAR NOT NULL);

CREATE TABLE PRODUCT(
	SKU INTEGER PRIMARY KEY,
	PRODUCT_NAME VARCHAR NOT NULL,
	CATEGORY_NAME VARCHAR REFERENCES CATEGORIES(CATEGORY_NAME) NOT NULL,
	PRICE DECIMAL(9,2) NOT NULL);

CREATE TABLE CATEGORIES(
	CATEGORY_NAME VARCHAR PRIMARY KEY,
	DESCRIPTION VARCHAR NOT NULL);

CREATE TABLE SHOPPING_CART(
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR NOT NULL,
	PRODUCT_SKU INTEGER REFERENCES PRODUCT(SKU) NOT NULL,
	PURCHASED BOOLEAN NOT NULL,
	QUANTITY INTEGER NOT NULL);

CREATE TABLE CART_PRICE (
	CART_PRICE_ID SERIAL PRIMARY KEY,
	CART_ID INTEGER REFERENCES SHOPPING_CART(ID) NOT NULL,
	TOTAL_PRICE DECIMAL(9,2) NOT NULL);

CREATE TABLE BUYS(
	BUYS_ID SERIAL PRIMARY KEY,
	NAME VARCHAR REFERENCES USER(NAME) NOT NULL,
	CREDIT_CARD_NUMBER INTEGER NOT NULL),
	PURCHASE_DATE DATE NOT NULL);
