CREATE TABLE USERS (
	NAME TEXT PRIMARY KEY,
	AGE INTEGER NOT NULL,
	ROLE TEXT NOT NULL,
	STATE TEXT NOT NULL);
    
CREATE TABLE CATEGORIES(
    CATEGORY_ID SERIAL PRIMARY KEY,
	CATEGORY_NAME TEXT UNIQUE NOT NULL,
	DESCRIPTION TEXT NOT NULL);

CREATE TABLE PRODUCT(
	SKU TEXT PRIMARY KEY,
	PRODUCT_NAME TEXT NOT NULL,
	CATEGORY_NAME TEXT REFERENCES CATEGORIES(CATEGORY_NAME) NOT NULL,
	PRICE DECIMAL(9,2) NOT NULL);

CREATE TABLE CARTS(
  ID SERIAL PRIMARY KEY,
  NAME TEXT REFERENCES USERS(NAME) NOT NULL,
  TOTAL_PRICE DECIMAL(9,2),
  PURCHASE_DATE DATE
);

CREATE TABLE ITEMS(
	PID SERIAL PRIMARY KEY,
  ID SERIAL REFERENCES CARTS(ID),
  SKU TEXT REFERENCES PRODUCT(SKU),
  QTY INT NOT NULL,
  PRICE DECIMAL(9,2) NOT NULL
);

